#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElaboratoBDD
{
	using System.Configuration;
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MODEL_AGENCY")]
	public partial class ModelAgencyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definizioni metodo Extensibility
    partial void OnCreated();
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    partial void InsertDocument(Document instance);
    partial void UpdateDocument(Document instance);
    partial void DeleteDocument(Document instance);
    partial void InsertEvent(Event instance);
    partial void UpdateEvent(Event instance);
    partial void DeleteEvent(Event instance);
    partial void InsertLocation(Location instance);
    partial void UpdateLocation(Location instance);
    partial void DeleteLocation(Location instance);
    partial void InsertManager(Manager instance);
    partial void UpdateManager(Manager instance);
    partial void DeleteManager(Manager instance);
    partial void InsertModel(Model instance);
    partial void UpdateModel(Model instance);
    partial void DeleteModel(Model instance);
    partial void InsertOffer(Offer instance);
    partial void UpdateOffer(Offer instance);
    partial void DeleteOffer(Offer instance);
    partial void InsertOfferType(OfferType instance);
    partial void UpdateOfferType(OfferType instance);
    partial void DeleteOfferType(OfferType instance);
    partial void InsertPhoto(Photo instance);
    partial void UpdatePhoto(Photo instance);
    partial void DeletePhoto(Photo instance);
    partial void Insertproposal(proposal instance);
    partial void Updateproposal(proposal instance);
    partial void Deleteproposal(proposal instance);
    partial void InsertSocial(Social instance);
    partial void UpdateSocial(Social instance);
    partial void DeleteSocial(Social instance);
    partial void InsertTransport(Transport instance);
    partial void UpdateTransport(Transport instance);
    partial void DeleteTransport(Transport instance);
    partial void InsertVideo(Video instance);
    partial void UpdateVideo(Video instance);
    partial void DeleteVideo(Video instance);
		#endregion

		public ModelAgencyDataContext() :
				base(ConfigurationManager.ConnectionStrings["Local"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModelAgencyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelAgencyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelAgencyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelAgencyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Customer> Customer
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
		
		public System.Data.Linq.Table<Document> Document
		{
			get
			{
				return this.GetTable<Document>();
			}
		}
		
		public System.Data.Linq.Table<Event> Event
		{
			get
			{
				return this.GetTable<Event>();
			}
		}
		
		public System.Data.Linq.Table<Location> Location
		{
			get
			{
				return this.GetTable<Location>();
			}
		}
		
		public System.Data.Linq.Table<Manager> Manager
		{
			get
			{
				return this.GetTable<Manager>();
			}
		}
		
		public System.Data.Linq.Table<Model> Model
		{
			get
			{
				return this.GetTable<Model>();
			}
		}
		
		public System.Data.Linq.Table<Offer> Offer
		{
			get
			{
				return this.GetTable<Offer>();
			}
		}
		
		public System.Data.Linq.Table<OfferType> OfferType
		{
			get
			{
				return this.GetTable<OfferType>();
			}
		}
		
		public System.Data.Linq.Table<Photo> Photo
		{
			get
			{
				return this.GetTable<Photo>();
			}
		}
		
		public System.Data.Linq.Table<proposal> proposal
		{
			get
			{
				return this.GetTable<proposal>();
			}
		}
		
		public System.Data.Linq.Table<Social> Social
		{
			get
			{
				return this.GetTable<Social>();
			}
		}
		
		public System.Data.Linq.Table<Transport> Transport
		{
			get
			{
				return this.GetTable<Transport>();
			}
		}
		
		public System.Data.Linq.Table<Video> Video
		{
			get
			{
				return this.GetTable<Video>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _iden_card_numb;
		
		private string _name;
		
		private string _surname;
		
		private System.Nullable<System.DateTime> _birth_date;
		
		private string _address;
		
		private string _P_IVA;
		
		private string _final_client;
		
		private EntitySet<Offer> _Offer;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oniden_card_numbChanging(string value);
    partial void Oniden_card_numbChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnsurnameChanging(string value);
    partial void OnsurnameChanged();
    partial void Onbirth_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onbirth_dateChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnP_IVAChanging(string value);
    partial void OnP_IVAChanged();
    partial void Onfinal_clientChanging(string value);
    partial void Onfinal_clientChanged();
    #endregion
		
		public Customer()
		{
			this._Offer = new EntitySet<Offer>(new Action<Offer>(this.attach_Offer), new Action<Offer>(this.detach_Offer));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iden_card_numb", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string iden_card_numb
		{
			get
			{
				return this._iden_card_numb;
			}
			set
			{
				if ((this._iden_card_numb != value))
				{
					this.Oniden_card_numbChanging(value);
					this.SendPropertyChanging();
					this._iden_card_numb = value;
					this.SendPropertyChanged("iden_card_numb");
					this.Oniden_card_numbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(20)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_surname", DbType="VarChar(20)")]
		public string surname
		{
			get
			{
				return this._surname;
			}
			set
			{
				if ((this._surname != value))
				{
					this.OnsurnameChanging(value);
					this.SendPropertyChanging();
					this._surname = value;
					this.SendPropertyChanged("surname");
					this.OnsurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birth_date", DbType="Date")]
		public System.Nullable<System.DateTime> birth_date
		{
			get
			{
				return this._birth_date;
			}
			set
			{
				if ((this._birth_date != value))
				{
					this.Onbirth_dateChanging(value);
					this.SendPropertyChanging();
					this._birth_date = value;
					this.SendPropertyChanged("birth_date");
					this.Onbirth_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_IVA", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string P_IVA
		{
			get
			{
				return this._P_IVA;
			}
			set
			{
				if ((this._P_IVA != value))
				{
					this.OnP_IVAChanging(value);
					this.SendPropertyChanging();
					this._P_IVA = value;
					this.SendPropertyChanged("P_IVA");
					this.OnP_IVAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_final_client", DbType="VarChar(50)")]
		public string final_client
		{
			get
			{
				return this._final_client;
			}
			set
			{
				if ((this._final_client != value))
				{
					this.Onfinal_clientChanging(value);
					this.SendPropertyChanging();
					this._final_client = value;
					this.SendPropertyChanged("final_client");
					this.Onfinal_clientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_Offer", Storage="_Offer", ThisKey="iden_card_numb", OtherKey="customer_iden_card_numb")]
		public EntitySet<Offer> Offer
		{
			get
			{
				return this._Offer;
			}
			set
			{
				this._Offer.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Offer(Offer entity)
		{
			this.SendPropertyChanging();
			entity.Customer = this;
		}
		
		private void detach_Offer(Offer entity)
		{
			this.SendPropertyChanging();
			entity.Customer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Document")]
	public partial class Document : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _name;
		
		private System.Nullable<int> _size;
		
		private string _path;
		
		private string _type;
		
		private string _model_iden_card_numb;
		
		private EntityRef<Model> _Model;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnsizeChanging(System.Nullable<int> value);
    partial void OnsizeChanged();
    partial void OnpathChanging(string value);
    partial void OnpathChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void Onmodel_iden_card_numbChanging(string value);
    partial void Onmodel_iden_card_numbChanged();
    #endregion
		
		public Document()
		{
			this._Model = default(EntityRef<Model>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size", DbType="Int")]
		public System.Nullable<int> size
		{
			get
			{
				return this._size;
			}
			set
			{
				if ((this._size != value))
				{
					this.OnsizeChanging(value);
					this.SendPropertyChanging();
					this._size = value;
					this.SendPropertyChanged("size");
					this.OnsizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_path", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string path
		{
			get
			{
				return this._path;
			}
			set
			{
				if ((this._path != value))
				{
					this.OnpathChanging(value);
					this.SendPropertyChanging();
					this._path = value;
					this.SendPropertyChanged("path");
					this.OnpathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model_iden_card_numb", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string model_iden_card_numb
		{
			get
			{
				return this._model_iden_card_numb;
			}
			set
			{
				if ((this._model_iden_card_numb != value))
				{
					if (this._Model.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmodel_iden_card_numbChanging(value);
					this.SendPropertyChanging();
					this._model_iden_card_numb = value;
					this.SendPropertyChanged("model_iden_card_numb");
					this.Onmodel_iden_card_numbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Model_Document", Storage="_Model", ThisKey="model_iden_card_numb", OtherKey="iden_card_numb", IsForeignKey=true)]
		public Model Model
		{
			get
			{
				return this._Model.Entity;
			}
			set
			{
				Model previousValue = this._Model.Entity;
				if (((previousValue != value) 
							|| (this._Model.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Model.Entity = null;
						previousValue.Document.Remove(this);
					}
					this._Model.Entity = value;
					if ((value != null))
					{
						value.Document.Add(this);
						this._model_iden_card_numb = value.iden_card_numb;
					}
					else
					{
						this._model_iden_card_numb = default(string);
					}
					this.SendPropertyChanged("Model");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Event")]
	public partial class Event : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codOffer;
		
		private System.DateTime _offer_date;
		
		private int _codEvent;
		
		private System.DateTime _start_time;
		
		private System.DateTime _end_time;
		
		private string _model_iden_card_numb;
		
		private int _transport_ID;
		
		private EntityRef<Model> _Model;
		
		private EntityRef<Offer> _Offer;
		
		private EntityRef<Transport> _Transport;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodOfferChanging(int value);
    partial void OncodOfferChanged();
    partial void Onoffer_dateChanging(System.DateTime value);
    partial void Onoffer_dateChanged();
    partial void OncodEventChanging(int value);
    partial void OncodEventChanged();
    partial void Onstart_timeChanging(System.DateTime value);
    partial void Onstart_timeChanged();
    partial void Onend_timeChanging(System.DateTime value);
    partial void Onend_timeChanged();
    partial void Onmodel_iden_card_numbChanging(string value);
    partial void Onmodel_iden_card_numbChanged();
    partial void Ontransport_IDChanging(int value);
    partial void Ontransport_IDChanged();
    #endregion
		
		public Event()
		{
			this._Model = default(EntityRef<Model>);
			this._Offer = default(EntityRef<Offer>);
			this._Transport = default(EntityRef<Transport>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codOffer", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int codOffer
		{
			get
			{
				return this._codOffer;
			}
			set
			{
				if ((this._codOffer != value))
				{
					if (this._Offer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodOfferChanging(value);
					this.SendPropertyChanging();
					this._codOffer = value;
					this.SendPropertyChanged("codOffer");
					this.OncodOfferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_offer_date", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime offer_date
		{
			get
			{
				return this._offer_date;
			}
			set
			{
				if ((this._offer_date != value))
				{
					if (this._Offer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onoffer_dateChanging(value);
					this.SendPropertyChanging();
					this._offer_date = value;
					this.SendPropertyChanged("offer_date");
					this.Onoffer_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEvent", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codEvent
		{
			get
			{
				return this._codEvent;
			}
			set
			{
				if ((this._codEvent != value))
				{
					this.OncodEventChanging(value);
					this.SendPropertyChanging();
					this._codEvent = value;
					this.SendPropertyChanged("codEvent");
					this.OncodEventChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_time", DbType="DateTime NOT NULL")]
		public System.DateTime start_time
		{
			get
			{
				return this._start_time;
			}
			set
			{
				if ((this._start_time != value))
				{
					this.Onstart_timeChanging(value);
					this.SendPropertyChanging();
					this._start_time = value;
					this.SendPropertyChanged("start_time");
					this.Onstart_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_time", DbType="DateTime NOT NULL")]
		public System.DateTime end_time
		{
			get
			{
				return this._end_time;
			}
			set
			{
				if ((this._end_time != value))
				{
					this.Onend_timeChanging(value);
					this.SendPropertyChanging();
					this._end_time = value;
					this.SendPropertyChanged("end_time");
					this.Onend_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model_iden_card_numb", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string model_iden_card_numb
		{
			get
			{
				return this._model_iden_card_numb;
			}
			set
			{
				if ((this._model_iden_card_numb != value))
				{
					if (this._Model.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmodel_iden_card_numbChanging(value);
					this.SendPropertyChanging();
					this._model_iden_card_numb = value;
					this.SendPropertyChanged("model_iden_card_numb");
					this.Onmodel_iden_card_numbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transport_ID", DbType="Int NOT NULL")]
		public int transport_ID
		{
			get
			{
				return this._transport_ID;
			}
			set
			{
				if ((this._transport_ID != value))
				{
					if (this._Transport.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontransport_IDChanging(value);
					this.SendPropertyChanging();
					this._transport_ID = value;
					this.SendPropertyChanged("transport_ID");
					this.Ontransport_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Model_Event", Storage="_Model", ThisKey="model_iden_card_numb", OtherKey="iden_card_numb", IsForeignKey=true)]
		public Model Model
		{
			get
			{
				return this._Model.Entity;
			}
			set
			{
				Model previousValue = this._Model.Entity;
				if (((previousValue != value) 
							|| (this._Model.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Model.Entity = null;
						previousValue.Event.Remove(this);
					}
					this._Model.Entity = value;
					if ((value != null))
					{
						value.Event.Add(this);
						this._model_iden_card_numb = value.iden_card_numb;
					}
					else
					{
						this._model_iden_card_numb = default(string);
					}
					this.SendPropertyChanged("Model");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Offer_Event", Storage="_Offer", ThisKey="codOffer,offer_date", OtherKey="codOffer,date_", IsForeignKey=true)]
		public Offer Offer
		{
			get
			{
				return this._Offer.Entity;
			}
			set
			{
				Offer previousValue = this._Offer.Entity;
				if (((previousValue != value) 
							|| (this._Offer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Offer.Entity = null;
						previousValue.Event.Remove(this);
					}
					this._Offer.Entity = value;
					if ((value != null))
					{
						value.Event.Add(this);
						this._codOffer = value.codOffer;
						this._offer_date = value.date_;
					}
					else
					{
						this._codOffer = default(int);
						this._offer_date = default(System.DateTime);
					}
					this.SendPropertyChanged("Offer");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Transport_Event", Storage="_Transport", ThisKey="transport_ID", OtherKey="ID", IsForeignKey=true)]
		public Transport Transport
		{
			get
			{
				return this._Transport.Entity;
			}
			set
			{
				Transport previousValue = this._Transport.Entity;
				if (((previousValue != value) 
							|| (this._Transport.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Transport.Entity = null;
						previousValue.Event.Remove(this);
					}
					this._Transport.Entity = value;
					if ((value != null))
					{
						value.Event.Add(this);
						this._transport_ID = value.ID;
					}
					else
					{
						this._transport_ID = default(int);
					}
					this.SendPropertyChanged("Transport");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Location")]
	public partial class Location : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CAP;
		
		private string _Avenue;
		
		private string _City;
		
		private int _Number;
		
		private string _Country;
		
		private EntitySet<Offer> _Offer;

		public string Row => $"{_CAP} {_Avenue} {_City} {_Number} {_Country}";
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCAPChanging(string value);
    partial void OnCAPChanged();
    partial void OnAvenueChanging(string value);
    partial void OnAvenueChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnNumberChanging(int value);
    partial void OnNumberChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    #endregion
		
		public Location()
		{
			this._Offer = new EntitySet<Offer>(new Action<Offer>(this.attach_Offer), new Action<Offer>(this.detach_Offer));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAP", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string CAP
		{
			get
			{
				return this._CAP;
			}
			set
			{
				if ((this._CAP != value))
				{
					this.OnCAPChanging(value);
					this.SendPropertyChanging();
					this._CAP = value;
					this.SendPropertyChanged("CAP");
					this.OnCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avenue", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Avenue
		{
			get
			{
				return this._Avenue;
			}
			set
			{
				if ((this._Avenue != value))
				{
					this.OnAvenueChanging(value);
					this.SendPropertyChanging();
					this._Avenue = value;
					this.SendPropertyChanged("Avenue");
					this.OnAvenueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="Int NOT NULL")]
		public int Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this.OnNumberChanging(value);
					this.SendPropertyChanging();
					this._Number = value;
					this.SendPropertyChanged("Number");
					this.OnNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Location_Offer", Storage="_Offer", ThisKey="ID", OtherKey="location_ID")]
		public EntitySet<Offer> Offer
		{
			get
			{
				return this._Offer;
			}
			set
			{
				this._Offer.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Offer(Offer entity)
		{
			this.SendPropertyChanging();
			entity.Location = this;
		}
		
		private void detach_Offer(Offer entity)
		{
			this.SendPropertyChanging();
			entity.Location = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Manager")]
	public partial class Manager : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _iden_card_numb;
		
		private string _name;
		
		private string _surname;
		
		private System.Nullable<System.DateTime> _birth_date;
		
		private string _address;
		
		private EntitySet<Model> _Model;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oniden_card_numbChanging(string value);
    partial void Oniden_card_numbChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnsurnameChanging(string value);
    partial void OnsurnameChanged();
    partial void Onbirth_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onbirth_dateChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    #endregion
		
		public Manager()
		{
			this._Model = new EntitySet<Model>(new Action<Model>(this.attach_Model), new Action<Model>(this.detach_Model));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iden_card_numb", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string iden_card_numb
		{
			get
			{
				return this._iden_card_numb;
			}
			set
			{
				if ((this._iden_card_numb != value))
				{
					this.Oniden_card_numbChanging(value);
					this.SendPropertyChanging();
					this._iden_card_numb = value;
					this.SendPropertyChanged("iden_card_numb");
					this.Oniden_card_numbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(20)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_surname", DbType="VarChar(20)")]
		public string surname
		{
			get
			{
				return this._surname;
			}
			set
			{
				if ((this._surname != value))
				{
					this.OnsurnameChanging(value);
					this.SendPropertyChanging();
					this._surname = value;
					this.SendPropertyChanged("surname");
					this.OnsurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birth_date", DbType="Date")]
		public System.Nullable<System.DateTime> birth_date
		{
			get
			{
				return this._birth_date;
			}
			set
			{
				if ((this._birth_date != value))
				{
					this.Onbirth_dateChanging(value);
					this.SendPropertyChanging();
					this._birth_date = value;
					this.SendPropertyChanged("birth_date");
					this.Onbirth_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Manager_Model", Storage="_Model", ThisKey="iden_card_numb", OtherKey="manager_iden_card_numb")]
		public EntitySet<Model> Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				this._Model.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Model(Model entity)
		{
			this.SendPropertyChanging();
			entity.Manager = this;
		}
		
		private void detach_Model(Model entity)
		{
			this.SendPropertyChanging();
			entity.Manager = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Model")]
	public partial class Model : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _iden_card_numb;
		
		private string _name;
		
		private string _surname;
		
		private System.Nullable<System.DateTime> _birth_date;
		
		private string _address;
		
		private string _eyes_color;
		
		private System.Nullable<int> _age;
		
		private string _email;
		
		private string _hair_color;
		
		private System.Nullable<int> _shoes_number;
		
		private System.Nullable<decimal> _height;
		
		private System.Nullable<decimal> _waist;
		
		private System.Nullable<decimal> _success_rate;
		
		private string _manager_iden_card_numb;
		
		private EntitySet<Document> _Document;
		
		private EntitySet<Event> _Event;
		
		private EntitySet<Photo> _Photo;
		
		private EntitySet<proposal> _proposal;
		
		private EntitySet<Social> _Social;
		
		private EntitySet<Video> _Video;
		
		private EntityRef<Manager> _Manager;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oniden_card_numbChanging(string value);
    partial void Oniden_card_numbChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnsurnameChanging(string value);
    partial void OnsurnameChanged();
    partial void Onbirth_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onbirth_dateChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void Oneyes_colorChanging(string value);
    partial void Oneyes_colorChanged();
    partial void OnageChanging(System.Nullable<int> value);
    partial void OnageChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onhair_colorChanging(string value);
    partial void Onhair_colorChanged();
    partial void Onshoes_numberChanging(System.Nullable<int> value);
    partial void Onshoes_numberChanged();
    partial void OnheightChanging(System.Nullable<decimal> value);
    partial void OnheightChanged();
    partial void OnwaistChanging(System.Nullable<decimal> value);
    partial void OnwaistChanged();
    partial void Onsuccess_rateChanging(System.Nullable<decimal> value);
    partial void Onsuccess_rateChanged();
    partial void Onmanager_iden_card_numbChanging(string value);
    partial void Onmanager_iden_card_numbChanged();
    #endregion
		
		public Model()
		{
			this._Document = new EntitySet<Document>(new Action<Document>(this.attach_Document), new Action<Document>(this.detach_Document));
			this._Event = new EntitySet<Event>(new Action<Event>(this.attach_Event), new Action<Event>(this.detach_Event));
			this._Photo = new EntitySet<Photo>(new Action<Photo>(this.attach_Photo), new Action<Photo>(this.detach_Photo));
			this._proposal = new EntitySet<proposal>(new Action<proposal>(this.attach_proposal), new Action<proposal>(this.detach_proposal));
			this._Social = new EntitySet<Social>(new Action<Social>(this.attach_Social), new Action<Social>(this.detach_Social));
			this._Video = new EntitySet<Video>(new Action<Video>(this.attach_Video), new Action<Video>(this.detach_Video));
			this._Manager = default(EntityRef<Manager>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iden_card_numb", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string iden_card_numb
		{
			get
			{
				return this._iden_card_numb;
			}
			set
			{
				if ((this._iden_card_numb != value))
				{
					this.Oniden_card_numbChanging(value);
					this.SendPropertyChanging();
					this._iden_card_numb = value;
					this.SendPropertyChanged("iden_card_numb");
					this.Oniden_card_numbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(20)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_surname", DbType="VarChar(20)")]
		public string surname
		{
			get
			{
				return this._surname;
			}
			set
			{
				if ((this._surname != value))
				{
					this.OnsurnameChanging(value);
					this.SendPropertyChanging();
					this._surname = value;
					this.SendPropertyChanged("surname");
					this.OnsurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birth_date", DbType="Date")]
		public System.Nullable<System.DateTime> birth_date
		{
			get
			{
				return this._birth_date;
			}
			set
			{
				if ((this._birth_date != value))
				{
					this.Onbirth_dateChanging(value);
					this.SendPropertyChanging();
					this._birth_date = value;
					this.SendPropertyChanged("birth_date");
					this.Onbirth_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eyes_color", DbType="VarChar(20)")]
		public string eyes_color
		{
			get
			{
				return this._eyes_color;
			}
			set
			{
				if ((this._eyes_color != value))
				{
					this.Oneyes_colorChanging(value);
					this.SendPropertyChanging();
					this._eyes_color = value;
					this.SendPropertyChanged("eyes_color");
					this.Oneyes_colorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this.OnageChanging(value);
					this.SendPropertyChanging();
					this._age = value;
					this.SendPropertyChanged("age");
					this.OnageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hair_color", DbType="VarChar(20)")]
		public string hair_color
		{
			get
			{
				return this._hair_color;
			}
			set
			{
				if ((this._hair_color != value))
				{
					this.Onhair_colorChanging(value);
					this.SendPropertyChanging();
					this._hair_color = value;
					this.SendPropertyChanged("hair_color");
					this.Onhair_colorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shoes_number", DbType="Int")]
		public System.Nullable<int> shoes_number
		{
			get
			{
				return this._shoes_number;
			}
			set
			{
				if ((this._shoes_number != value))
				{
					this.Onshoes_numberChanging(value);
					this.SendPropertyChanging();
					this._shoes_number = value;
					this.SendPropertyChanged("shoes_number");
					this.Onshoes_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_height", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> height
		{
			get
			{
				return this._height;
			}
			set
			{
				if ((this._height != value))
				{
					this.OnheightChanging(value);
					this.SendPropertyChanging();
					this._height = value;
					this.SendPropertyChanged("height");
					this.OnheightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_waist", DbType="Decimal(3,1)")]
		public System.Nullable<decimal> waist
		{
			get
			{
				return this._waist;
			}
			set
			{
				if ((this._waist != value))
				{
					this.OnwaistChanging(value);
					this.SendPropertyChanging();
					this._waist = value;
					this.SendPropertyChanged("waist");
					this.OnwaistChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_success_rate", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> success_rate
		{
			get
			{
				return this._success_rate;
			}
			set
			{
				if ((this._success_rate != value))
				{
					this.Onsuccess_rateChanging(value);
					this.SendPropertyChanging();
					this._success_rate = value;
					this.SendPropertyChanged("success_rate");
					this.Onsuccess_rateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manager_iden_card_numb", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string manager_iden_card_numb
		{
			get
			{
				return this._manager_iden_card_numb;
			}
			set
			{
				if ((this._manager_iden_card_numb != value))
				{
					if (this._Manager.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmanager_iden_card_numbChanging(value);
					this.SendPropertyChanging();
					this._manager_iden_card_numb = value;
					this.SendPropertyChanged("manager_iden_card_numb");
					this.Onmanager_iden_card_numbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Model_Document", Storage="_Document", ThisKey="iden_card_numb", OtherKey="model_iden_card_numb")]
		public EntitySet<Document> Document
		{
			get
			{
				return this._Document;
			}
			set
			{
				this._Document.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Model_Event", Storage="_Event", ThisKey="iden_card_numb", OtherKey="model_iden_card_numb")]
		public EntitySet<Event> Event
		{
			get
			{
				return this._Event;
			}
			set
			{
				this._Event.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Model_Photo", Storage="_Photo", ThisKey="iden_card_numb", OtherKey="model_iden_card_numb")]
		public EntitySet<Photo> Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				this._Photo.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Model_proposal", Storage="_proposal", ThisKey="iden_card_numb", OtherKey="model_iden_card_numb")]
		public EntitySet<proposal> proposal
		{
			get
			{
				return this._proposal;
			}
			set
			{
				this._proposal.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Model_Social", Storage="_Social", ThisKey="iden_card_numb", OtherKey="model_iden_card_numb")]
		public EntitySet<Social> Social
		{
			get
			{
				return this._Social;
			}
			set
			{
				this._Social.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Model_Video", Storage="_Video", ThisKey="iden_card_numb", OtherKey="model_iden_card_numb")]
		public EntitySet<Video> Video
		{
			get
			{
				return this._Video;
			}
			set
			{
				this._Video.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Manager_Model", Storage="_Manager", ThisKey="manager_iden_card_numb", OtherKey="iden_card_numb", IsForeignKey=true)]
		public Manager Manager
		{
			get
			{
				return this._Manager.Entity;
			}
			set
			{
				Manager previousValue = this._Manager.Entity;
				if (((previousValue != value) 
							|| (this._Manager.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Manager.Entity = null;
						previousValue.Model.Remove(this);
					}
					this._Manager.Entity = value;
					if ((value != null))
					{
						value.Model.Add(this);
						this._manager_iden_card_numb = value.iden_card_numb;
					}
					else
					{
						this._manager_iden_card_numb = default(string);
					}
					this.SendPropertyChanged("Manager");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Document(Document entity)
		{
			this.SendPropertyChanging();
			entity.Model = this;
		}
		
		private void detach_Document(Document entity)
		{
			this.SendPropertyChanging();
			entity.Model = null;
		}
		
		private void attach_Event(Event entity)
		{
			this.SendPropertyChanging();
			entity.Model = this;
		}
		
		private void detach_Event(Event entity)
		{
			this.SendPropertyChanging();
			entity.Model = null;
		}
		
		private void attach_Photo(Photo entity)
		{
			this.SendPropertyChanging();
			entity.Model = this;
		}
		
		private void detach_Photo(Photo entity)
		{
			this.SendPropertyChanging();
			entity.Model = null;
		}
		
		private void attach_proposal(proposal entity)
		{
			this.SendPropertyChanging();
			entity.Model = this;
		}
		
		private void detach_proposal(proposal entity)
		{
			this.SendPropertyChanging();
			entity.Model = null;
		}
		
		private void attach_Social(Social entity)
		{
			this.SendPropertyChanging();
			entity.Model = this;
		}
		
		private void detach_Social(Social entity)
		{
			this.SendPropertyChanging();
			entity.Model = null;
		}
		
		private void attach_Video(Video entity)
		{
			this.SendPropertyChanging();
			entity.Model = this;
		}
		
		private void detach_Video(Video entity)
		{
			this.SendPropertyChanging();
			entity.Model = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Offer")]
	public partial class Offer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<System.DateTime> _approval_date;
		
		private int _codOffer;
		
		private System.DateTime _date_;
		
		private string _status;
		
		private int _requested_models;
		
		private string _short_description;
		
		private string _long_description;
		
		private System.Nullable<int> _budget;
		
		private string _offer_type_name;
		
		private int _location_ID;
		
		private string _customer_iden_card_numb;
		
		private EntitySet<Event> _Event;
		
		private EntitySet<proposal> _proposal;
		
		private EntityRef<Customer> _Customer;
		
		private EntityRef<Location> _Location;
		
		private EntityRef<OfferType> _OfferType;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onapproval_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onapproval_dateChanged();
    partial void OncodOfferChanging(int value);
    partial void OncodOfferChanged();
    partial void Ondate_Changing(System.DateTime value);
    partial void Ondate_Changed();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void Onrequested_modelsChanging(int value);
    partial void Onrequested_modelsChanged();
    partial void Onshort_descriptionChanging(string value);
    partial void Onshort_descriptionChanged();
    partial void Onlong_descriptionChanging(string value);
    partial void Onlong_descriptionChanged();
    partial void OnbudgetChanging(System.Nullable<int> value);
    partial void OnbudgetChanged();
    partial void Onoffer_type_nameChanging(string value);
    partial void Onoffer_type_nameChanged();
    partial void Onlocation_IDChanging(int value);
    partial void Onlocation_IDChanged();
    partial void Oncustomer_iden_card_numbChanging(string value);
    partial void Oncustomer_iden_card_numbChanged();
    #endregion
		
		public Offer()
		{
			this._Event = new EntitySet<Event>(new Action<Event>(this.attach_Event), new Action<Event>(this.detach_Event));
			this._proposal = new EntitySet<proposal>(new Action<proposal>(this.attach_proposal), new Action<proposal>(this.detach_proposal));
			this._Customer = default(EntityRef<Customer>);
			this._Location = default(EntityRef<Location>);
			this._OfferType = default(EntityRef<OfferType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_approval_date", DbType="Date")]
		public System.Nullable<System.DateTime> approval_date
		{
			get
			{
				return this._approval_date;
			}
			set
			{
				if ((this._approval_date != value))
				{
					this.Onapproval_dateChanging(value);
					this.SendPropertyChanging();
					this._approval_date = value;
					this.SendPropertyChanged("approval_date");
					this.Onapproval_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codOffer", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codOffer
		{
			get
			{
				return this._codOffer;
			}
			set
			{
				if ((this._codOffer != value))
				{
					this.OncodOfferChanging(value);
					this.SendPropertyChanging();
					this._codOffer = value;
					this.SendPropertyChanged("codOffer");
					this.OncodOfferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime date_
		{
			get
			{
				return this._date_;
			}
			set
			{
				if ((this._date_ != value))
				{
					this.Ondate_Changing(value);
					this.SendPropertyChanging();
					this._date_ = value;
					this.SendPropertyChanged("date_");
					this.Ondate_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requested_models", DbType="Int NOT NULL")]
		public int requested_models
		{
			get
			{
				return this._requested_models;
			}
			set
			{
				if ((this._requested_models != value))
				{
					this.Onrequested_modelsChanging(value);
					this.SendPropertyChanging();
					this._requested_models = value;
					this.SendPropertyChanged("requested_models");
					this.Onrequested_modelsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_short_description", DbType="VarChar(100)")]
		public string short_description
		{
			get
			{
				return this._short_description;
			}
			set
			{
				if ((this._short_description != value))
				{
					this.Onshort_descriptionChanging(value);
					this.SendPropertyChanging();
					this._short_description = value;
					this.SendPropertyChanged("short_description");
					this.Onshort_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_long_description", DbType="VarChar(100)")]
		public string long_description
		{
			get
			{
				return this._long_description;
			}
			set
			{
				if ((this._long_description != value))
				{
					this.Onlong_descriptionChanging(value);
					this.SendPropertyChanging();
					this._long_description = value;
					this.SendPropertyChanged("long_description");
					this.Onlong_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_budget", DbType="Int")]
		public System.Nullable<int> budget
		{
			get
			{
				return this._budget;
			}
			set
			{
				if ((this._budget != value))
				{
					this.OnbudgetChanging(value);
					this.SendPropertyChanging();
					this._budget = value;
					this.SendPropertyChanged("budget");
					this.OnbudgetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_offer_type_name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string offer_type_name
		{
			get
			{
				return this._offer_type_name;
			}
			set
			{
				if ((this._offer_type_name != value))
				{
					if (this._OfferType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onoffer_type_nameChanging(value);
					this.SendPropertyChanging();
					this._offer_type_name = value;
					this.SendPropertyChanged("offer_type_name");
					this.Onoffer_type_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location_ID", DbType="Int NOT NULL")]
		public int location_ID
		{
			get
			{
				return this._location_ID;
			}
			set
			{
				if ((this._location_ID != value))
				{
					if (this._Location.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onlocation_IDChanging(value);
					this.SendPropertyChanging();
					this._location_ID = value;
					this.SendPropertyChanged("location_ID");
					this.Onlocation_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_iden_card_numb", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string customer_iden_card_numb
		{
			get
			{
				return this._customer_iden_card_numb;
			}
			set
			{
				if ((this._customer_iden_card_numb != value))
				{
					if (this._Customer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncustomer_iden_card_numbChanging(value);
					this.SendPropertyChanging();
					this._customer_iden_card_numb = value;
					this.SendPropertyChanged("customer_iden_card_numb");
					this.Oncustomer_iden_card_numbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Offer_Event", Storage="_Event", ThisKey="codOffer,date_", OtherKey="codOffer,offer_date")]
		public EntitySet<Event> Event
		{
			get
			{
				return this._Event;
			}
			set
			{
				this._Event.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Offer_proposal", Storage="_proposal", ThisKey="codOffer,date_", OtherKey="codOffer,offer_date")]
		public EntitySet<proposal> proposal
		{
			get
			{
				return this._proposal;
			}
			set
			{
				this._proposal.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_Offer", Storage="_Customer", ThisKey="customer_iden_card_numb", OtherKey="iden_card_numb", IsForeignKey=true)]
		public Customer Customer
		{
			get
			{
				return this._Customer.Entity;
			}
			set
			{
				Customer previousValue = this._Customer.Entity;
				if (((previousValue != value) 
							|| (this._Customer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Customer.Entity = null;
						previousValue.Offer.Remove(this);
					}
					this._Customer.Entity = value;
					if ((value != null))
					{
						value.Offer.Add(this);
						this._customer_iden_card_numb = value.iden_card_numb;
					}
					else
					{
						this._customer_iden_card_numb = default(string);
					}
					this.SendPropertyChanged("Customer");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Location_Offer", Storage="_Location", ThisKey="location_ID", OtherKey="ID", IsForeignKey=true)]
		public Location Location
		{
			get
			{
				return this._Location.Entity;
			}
			set
			{
				Location previousValue = this._Location.Entity;
				if (((previousValue != value) 
							|| (this._Location.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Location.Entity = null;
						previousValue.Offer.Remove(this);
					}
					this._Location.Entity = value;
					if ((value != null))
					{
						value.Offer.Add(this);
						this._location_ID = value.ID;
					}
					else
					{
						this._location_ID = default(int);
					}
					this.SendPropertyChanged("Location");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OfferType_Offer", Storage="_OfferType", ThisKey="offer_type_name", OtherKey="name", IsForeignKey=true)]
		public OfferType OfferType
		{
			get
			{
				return this._OfferType.Entity;
			}
			set
			{
				OfferType previousValue = this._OfferType.Entity;
				if (((previousValue != value) 
							|| (this._OfferType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._OfferType.Entity = null;
						previousValue.Offer.Remove(this);
					}
					this._OfferType.Entity = value;
					if ((value != null))
					{
						value.Offer.Add(this);
						this._offer_type_name = value.name;
					}
					else
					{
						this._offer_type_name = default(string);
					}
					this.SendPropertyChanged("OfferType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Event(Event entity)
		{
			this.SendPropertyChanging();
			entity.Offer = this;
		}
		
		private void detach_Event(Event entity)
		{
			this.SendPropertyChanging();
			entity.Offer = null;
		}
		
		private void attach_proposal(proposal entity)
		{
			this.SendPropertyChanging();
			entity.Offer = this;
		}
		
		private void detach_proposal(proposal entity)
		{
			this.SendPropertyChanging();
			entity.Offer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OfferType")]
	public partial class OfferType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _name;
		
		private string _description;
		
		private EntitySet<Offer> _Offer;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    #endregion
		
		public OfferType()
		{
			this._Offer = new EntitySet<Offer>(new Action<Offer>(this.attach_Offer), new Action<Offer>(this.detach_Offer));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OfferType_Offer", Storage="_Offer", ThisKey="name", OtherKey="offer_type_name")]
		public EntitySet<Offer> Offer
		{
			get
			{
				return this._Offer;
			}
			set
			{
				this._Offer.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Offer(Offer entity)
		{
			this.SendPropertyChanging();
			entity.OfferType = this;
		}
		
		private void detach_Offer(Offer entity)
		{
			this.SendPropertyChanging();
			entity.OfferType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Photo")]
	public partial class Photo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _name;
		
		private System.Nullable<int> _size;
		
		private string _path;
		
		private string _model_iden_card_numb;
		
		private EntityRef<Model> _Model;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnsizeChanging(System.Nullable<int> value);
    partial void OnsizeChanged();
    partial void OnpathChanging(string value);
    partial void OnpathChanged();
    partial void Onmodel_iden_card_numbChanging(string value);
    partial void Onmodel_iden_card_numbChanged();
    #endregion
		
		public Photo()
		{
			this._Model = default(EntityRef<Model>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size", DbType="Int")]
		public System.Nullable<int> size
		{
			get
			{
				return this._size;
			}
			set
			{
				if ((this._size != value))
				{
					this.OnsizeChanging(value);
					this.SendPropertyChanging();
					this._size = value;
					this.SendPropertyChanged("size");
					this.OnsizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_path", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string path
		{
			get
			{
				return this._path;
			}
			set
			{
				if ((this._path != value))
				{
					this.OnpathChanging(value);
					this.SendPropertyChanging();
					this._path = value;
					this.SendPropertyChanged("path");
					this.OnpathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model_iden_card_numb", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string model_iden_card_numb
		{
			get
			{
				return this._model_iden_card_numb;
			}
			set
			{
				if ((this._model_iden_card_numb != value))
				{
					if (this._Model.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmodel_iden_card_numbChanging(value);
					this.SendPropertyChanging();
					this._model_iden_card_numb = value;
					this.SendPropertyChanged("model_iden_card_numb");
					this.Onmodel_iden_card_numbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Model_Photo", Storage="_Model", ThisKey="model_iden_card_numb", OtherKey="iden_card_numb", IsForeignKey=true)]
		public Model Model
		{
			get
			{
				return this._Model.Entity;
			}
			set
			{
				Model previousValue = this._Model.Entity;
				if (((previousValue != value) 
							|| (this._Model.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Model.Entity = null;
						previousValue.Photo.Remove(this);
					}
					this._Model.Entity = value;
					if ((value != null))
					{
						value.Photo.Add(this);
						this._model_iden_card_numb = value.iden_card_numb;
					}
					else
					{
						this._model_iden_card_numb = default(string);
					}
					this.SendPropertyChanged("Model");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.proposal")]
	public partial class proposal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _model_iden_card_numb;
		
		private int _codOffer;
		
		private System.DateTime _offer_date;
		
		private char _status;
		
		private EntityRef<Model> _Model;
		
		private EntityRef<Offer> _Offer;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onmodel_iden_card_numbChanging(string value);
    partial void Onmodel_iden_card_numbChanged();
    partial void OncodOfferChanging(int value);
    partial void OncodOfferChanged();
    partial void Onoffer_dateChanging(System.DateTime value);
    partial void Onoffer_dateChanged();
    partial void OnstatusChanging(char value);
    partial void OnstatusChanged();
    #endregion
		
		public proposal()
		{
			this._Model = default(EntityRef<Model>);
			this._Offer = default(EntityRef<Offer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model_iden_card_numb", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string model_iden_card_numb
		{
			get
			{
				return this._model_iden_card_numb;
			}
			set
			{
				if ((this._model_iden_card_numb != value))
				{
					if (this._Model.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmodel_iden_card_numbChanging(value);
					this.SendPropertyChanging();
					this._model_iden_card_numb = value;
					this.SendPropertyChanged("model_iden_card_numb");
					this.Onmodel_iden_card_numbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codOffer", DbType="Int NOT NULL")]
		public int codOffer
		{
			get
			{
				return this._codOffer;
			}
			set
			{
				if ((this._codOffer != value))
				{
					if (this._Offer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodOfferChanging(value);
					this.SendPropertyChanging();
					this._codOffer = value;
					this.SendPropertyChanged("codOffer");
					this.OncodOfferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_offer_date", DbType="Date NOT NULL")]
		public System.DateTime offer_date
		{
			get
			{
				return this._offer_date;
			}
			set
			{
				if ((this._offer_date != value))
				{
					if (this._Offer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onoffer_dateChanging(value);
					this.SendPropertyChanging();
					this._offer_date = value;
					this.SendPropertyChanged("offer_date");
					this.Onoffer_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Char(1) NOT NULL")]
		public char status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Model_proposal", Storage="_Model", ThisKey="model_iden_card_numb", OtherKey="iden_card_numb", IsForeignKey=true)]
		public Model Model
		{
			get
			{
				return this._Model.Entity;
			}
			set
			{
				Model previousValue = this._Model.Entity;
				if (((previousValue != value) 
							|| (this._Model.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Model.Entity = null;
						previousValue.proposal.Remove(this);
					}
					this._Model.Entity = value;
					if ((value != null))
					{
						value.proposal.Add(this);
						this._model_iden_card_numb = value.iden_card_numb;
					}
					else
					{
						this._model_iden_card_numb = default(string);
					}
					this.SendPropertyChanged("Model");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Offer_proposal", Storage="_Offer", ThisKey="codOffer,offer_date", OtherKey="codOffer,date_", IsForeignKey=true)]
		public Offer Offer
		{
			get
			{
				return this._Offer.Entity;
			}
			set
			{
				Offer previousValue = this._Offer.Entity;
				if (((previousValue != value) 
							|| (this._Offer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Offer.Entity = null;
						previousValue.proposal.Remove(this);
					}
					this._Offer.Entity = value;
					if ((value != null))
					{
						value.proposal.Add(this);
						this._codOffer = value.codOffer;
						this._offer_date = value.date_;
					}
					else
					{
						this._codOffer = default(int);
						this._offer_date = default(System.DateTime);
					}
					this.SendPropertyChanged("Offer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Social")]
	public partial class Social : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _model_iden_card_numb;
		
		private string _platform;
		
		private string _link;
		
		private string _username;
		
		private System.Nullable<int> _followers;
		
		private EntityRef<Model> _Model;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmodel_iden_card_numbChanging(string value);
    partial void Onmodel_iden_card_numbChanged();
    partial void OnplatformChanging(string value);
    partial void OnplatformChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnfollowersChanging(System.Nullable<int> value);
    partial void OnfollowersChanged();
    #endregion
		
		public Social()
		{
			this._Model = default(EntityRef<Model>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model_iden_card_numb", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string model_iden_card_numb
		{
			get
			{
				return this._model_iden_card_numb;
			}
			set
			{
				if ((this._model_iden_card_numb != value))
				{
					if (this._Model.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmodel_iden_card_numbChanging(value);
					this.SendPropertyChanging();
					this._model_iden_card_numb = value;
					this.SendPropertyChanged("model_iden_card_numb");
					this.Onmodel_iden_card_numbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_platform", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string platform
		{
			get
			{
				return this._platform;
			}
			set
			{
				if ((this._platform != value))
				{
					this.OnplatformChanging(value);
					this.SendPropertyChanging();
					this._platform = value;
					this.SendPropertyChanged("platform");
					this.OnplatformChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_followers", DbType="Int")]
		public System.Nullable<int> followers
		{
			get
			{
				return this._followers;
			}
			set
			{
				if ((this._followers != value))
				{
					this.OnfollowersChanging(value);
					this.SendPropertyChanging();
					this._followers = value;
					this.SendPropertyChanged("followers");
					this.OnfollowersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Model_Social", Storage="_Model", ThisKey="model_iden_card_numb", OtherKey="iden_card_numb", IsForeignKey=true)]
		public Model Model
		{
			get
			{
				return this._Model.Entity;
			}
			set
			{
				Model previousValue = this._Model.Entity;
				if (((previousValue != value) 
							|| (this._Model.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Model.Entity = null;
						previousValue.Social.Remove(this);
					}
					this._Model.Entity = value;
					if ((value != null))
					{
						value.Social.Add(this);
						this._model_iden_card_numb = value.iden_card_numb;
					}
					else
					{
						this._model_iden_card_numb = default(string);
					}
					this.SendPropertyChanged("Model");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transport")]
	public partial class Transport : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _type;
		
		private string _description;
		
		private System.DateTime _start_datetime;
		
		private System.Nullable<System.DateTime> _arrival_datetime;
		
		private string _departure_place;
		
		private string _destination_place;
		
		private EntitySet<Event> _Event;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Onstart_datetimeChanging(System.DateTime value);
    partial void Onstart_datetimeChanged();
    partial void Onarrival_datetimeChanging(System.Nullable<System.DateTime> value);
    partial void Onarrival_datetimeChanged();
    partial void Ondeparture_placeChanging(string value);
    partial void Ondeparture_placeChanged();
    partial void Ondestination_placeChanging(string value);
    partial void Ondestination_placeChanged();
    #endregion
		
		public Transport()
		{
			this._Event = new EntitySet<Event>(new Action<Event>(this.attach_Event), new Action<Event>(this.detach_Event));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_datetime", DbType="DateTime NOT NULL")]
		public System.DateTime start_datetime
		{
			get
			{
				return this._start_datetime;
			}
			set
			{
				if ((this._start_datetime != value))
				{
					this.Onstart_datetimeChanging(value);
					this.SendPropertyChanging();
					this._start_datetime = value;
					this.SendPropertyChanged("start_datetime");
					this.Onstart_datetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arrival_datetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> arrival_datetime
		{
			get
			{
				return this._arrival_datetime;
			}
			set
			{
				if ((this._arrival_datetime != value))
				{
					this.Onarrival_datetimeChanging(value);
					this.SendPropertyChanging();
					this._arrival_datetime = value;
					this.SendPropertyChanged("arrival_datetime");
					this.Onarrival_datetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departure_place", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string departure_place
		{
			get
			{
				return this._departure_place;
			}
			set
			{
				if ((this._departure_place != value))
				{
					this.Ondeparture_placeChanging(value);
					this.SendPropertyChanging();
					this._departure_place = value;
					this.SendPropertyChanged("departure_place");
					this.Ondeparture_placeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destination_place", DbType="VarChar(50)")]
		public string destination_place
		{
			get
			{
				return this._destination_place;
			}
			set
			{
				if ((this._destination_place != value))
				{
					this.Ondestination_placeChanging(value);
					this.SendPropertyChanging();
					this._destination_place = value;
					this.SendPropertyChanged("destination_place");
					this.Ondestination_placeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Transport_Event", Storage="_Event", ThisKey="ID", OtherKey="transport_ID")]
		public EntitySet<Event> Event
		{
			get
			{
				return this._Event;
			}
			set
			{
				this._Event.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Event(Event entity)
		{
			this.SendPropertyChanging();
			entity.Transport = this;
		}
		
		private void detach_Event(Event entity)
		{
			this.SendPropertyChanging();
			entity.Transport = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Video")]
	public partial class Video : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _name;
		
		private System.Nullable<int> _size;
		
		private string _path;
		
		private string _model_iden_card_numb;
		
		private EntityRef<Model> _Model;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnsizeChanging(System.Nullable<int> value);
    partial void OnsizeChanged();
    partial void OnpathChanging(string value);
    partial void OnpathChanged();
    partial void Onmodel_iden_card_numbChanging(string value);
    partial void Onmodel_iden_card_numbChanged();
    #endregion
		
		public Video()
		{
			this._Model = default(EntityRef<Model>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size", DbType="Int")]
		public System.Nullable<int> size
		{
			get
			{
				return this._size;
			}
			set
			{
				if ((this._size != value))
				{
					this.OnsizeChanging(value);
					this.SendPropertyChanging();
					this._size = value;
					this.SendPropertyChanged("size");
					this.OnsizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_path", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string path
		{
			get
			{
				return this._path;
			}
			set
			{
				if ((this._path != value))
				{
					this.OnpathChanging(value);
					this.SendPropertyChanging();
					this._path = value;
					this.SendPropertyChanged("path");
					this.OnpathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model_iden_card_numb", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string model_iden_card_numb
		{
			get
			{
				return this._model_iden_card_numb;
			}
			set
			{
				if ((this._model_iden_card_numb != value))
				{
					if (this._Model.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmodel_iden_card_numbChanging(value);
					this.SendPropertyChanging();
					this._model_iden_card_numb = value;
					this.SendPropertyChanged("model_iden_card_numb");
					this.Onmodel_iden_card_numbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Model_Video", Storage="_Model", ThisKey="model_iden_card_numb", OtherKey="iden_card_numb", IsForeignKey=true)]
		public Model Model
		{
			get
			{
				return this._Model.Entity;
			}
			set
			{
				Model previousValue = this._Model.Entity;
				if (((previousValue != value) 
							|| (this._Model.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Model.Entity = null;
						previousValue.Video.Remove(this);
					}
					this._Model.Entity = value;
					if ((value != null))
					{
						value.Video.Add(this);
						this._model_iden_card_numb = value.iden_card_numb;
					}
					else
					{
						this._model_iden_card_numb = default(string);
					}
					this.SendPropertyChanged("Model");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
